# Generated by Django 2.0.3 on 2019-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_auto_20190322_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=1, unique=True, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
