# Generated by Django 2.0.3 on 2019-03-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0003_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
