# Generated by Django 2.0.3 on 2019-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180405_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='background',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
