# Generated by Django 2.0.3 on 2019-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='background',
            field=models.CharField(max_length=255),
        ),
    ]
