# Generated by Django 2.0.3 on 2019-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20190328_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='background',
            field=models.TextField(max_length=255),
        ),
    ]
