# Generated by Django 2.0.3 on 2019-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20190328_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
