# Generated by Django 2.0.3 on 2019-03-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20190328_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='background',
            field=models.TextField(),
        ),
    ]
