# Generated by Django 2.0.3 on 2019-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20190328_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='db_url',
            field=models.TextField(blank=True),
        ),
    ]
